### ISSUE TITLE
Submit to the plugin directory

### ISSUE THREAD

**Issue by bayleedev** [jgoday/zazu-dev-doc#1]
Have you thought about submitting your plugin to the zazu plugin directory?

http://zazuapp.org/plugins/

**Comment by jgoday** [comment]
Yes I have, but i'm not completely sure about how to proceed. Do i write it directly on the main repository (https://github.com/tinytacoteam/zazu/tree/master/docs/_packages) ? 
There is no revision process ?

**Comment by bayleedev** [comment]
Exactly, just submit a pr and I'll merge it in :D
